insert into users (
        username,
        password,
        gender,
        date_of_birth,
        contact_no,
        created_at
    )
VALUES (
        'Peter',
        'dhakjd',
        'M',
        '1999-01-03',
        '99991234',
        NOW()
    ),
    (
        'May',
        'dhadskjd',
        'F',
        '1998-02-03',
        '99884567',
        NOW()
    ),
    (
        'John',
        'dhadsdadskjd',
        'M',
        '2000-10-07',
        '99667897',
        NOW()
    );